### ISSUE TITLE
Lava functions strangely

### ISSUE THREAD

**Issue by RubyPiec** [Seb-135/ee-offline#1]
So, I am assuming that the ee offline on https://everybodyedits.com/ is this one. Basically, what's happening is that I would normally be able to go through a section filled with lava, but now I can't, lava also doesnt slow you dwon which it used to do.

**Comment by Seb-135** [comment]
Lava most definitely still slows you down - Just tested this on both https://everybodyedits.com/, and by downloading and re-building the source code.
As for being unable to go through a section filled with lava, this used to be an unintended side effect, discovered on 2020-12-01. Because EEO is, well, offline, there isn't a server to handle effect timers. The lag disappeared completely from effects like being on fire, and thus the time you spent alive was shorter.
The bug is visible here, reported by Fanbry on the EEU discord:
EEO: 
![](https://cdn.discordapp.com/attachments/682653647103983622/783121073008410675/LavaEE.gif)

EE: 
![](https://cdn.discordapp.com/attachments/682653647103983622/783121097431318528/LavaEE2.gif)

The bug has since been fixed. Recreating the exact same setup in EEO, you can now see for yourself that you can clear 7 lava blocks, exactly the same as you could in EE:

https://user-images.githubusercontent.com/76539951/103485126-26974300-4dec-11eb-96b4-f13e119064c0.mp4


Here's the world download, for your convenience:
https://www.mediafire.com/file/zmxhbcy3s8wnptm/Lava+Bug+-+seb135.eelvl/file
